### ISSUE TITLE
导入jar包失败

### ISSUE THREAD

**Issue by yuezhuxue** [XiaoYuOvO/MITE-ITE#1]
引用1.6.4-MITE.jar包失败导致无法编译，想请教一下您是如何处理的

https://gitee.com/yuezhuxue/yuezhuxue/raw/master/images/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE20201014141918.jpg

https://gitee.com/yuezhuxue/yuezhuxue/raw/master/images/%E6%90%9C%E7%8B%97%E6%88%AA%E5%9B%BE20201014141933.jpg

**Comment by XiaoYuOvO** [comment]
首先请先安装一个FishModLoader到你的游戏上并加入MITE-ITE模组,然后启动一次,关闭,修改.minecraft文件夹下面的config.json文件,改为如下所示:

**Comment by XiaoYuOvO** [comment]
```
{
  "debug": true,
  "jarPath": "source.jar",
  "dumpClass": true,
  "dumpPath": <类文件输出文件夹>,
  "dumpFilter": "minecraft",
  "printClassLoadInfo": false,
  "cleanClassImplementation": true,
  "fpsLimit": 200
}
```

**Comment by XiaoYuOvO** [comment]
再启动一次
然后Minecraft的类文件将会输出到那个文件夹内(如果有的类在启动后没有生成,就请进行一次与这个类文件名称相关的游戏内活动[因为只有被触发类加载后才会被导出])
这时你再将类文件输出目录作为库导入即可
(建议导出之后如果不需要再次导出,就将配置文件的dumpClass改为false,不然每次启动IDEA都会卡一下[索引类文件])

**Comment by yuezhuxue** [comment]
解决了。十分感谢！
